sonar.projectKey=TS-node-boilerpate
sonar.projectName=TS node boilerplate
sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN}

# Point Sonar to Jest LCOV report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Analyze only src
sonar.sources=src

# Optional: explicitly mark tests
sonar.tests=src
sonar.test.inclusions=**/__tests__/**/*.(spec|test).ts
sonar.typescript.tsconfigPath=tsconfig.json

# Exclude non-source folders (even though sonar.sources=src already limits it)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.scannerwork/**,**/.sonar/**
sonar.coverage.exclusions=src/**/*.spec.ts,src/**/*.test.ts,src/branded-types.ts

sonar.sourceEncoding=UTF-8
